---
name: image_building
kind: pipeline
type: docker

steps:
# nginx
  - name: build nginx:test1
    image: plugins/docker
    depends_on:
      - clone
    privileged: true
    settings:
      repo: registry.nextpertise.tools/nextpertise/michaelnginx
      registry: registry.nextpertise.tools
      dockerfile: build/web/Dockerfile
      pull_image: true
      context: build/web/
      build_args:
        - tag=test1
      username:
        from_secret: platform_harbor_username
      password:
        from_secret: platform_harbor_password
      tags:
        - test1
#php
  - name: build php:test1
    image: plugins/docker
    depends_on:
      - clone
    privileged: true
    settings:
      repo: registry.nextpertise.tools/nextpertise/michaelphp
      registry: registry.nextpertise.tools
      dockerfile: build/php/Dockerfile
      pull_image: true
      context: build/php/
      build_args:
        - tag=test1
      username:
        from_secret: platform_harbor_username
      password:
        from_secret: platform_harbor_password
      tags:
        - test1
image_pull_secrets:
  - platform_harbor_pull_secrets

---
name: deployment
kind: pipeline
name: deploy

steps:
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: rke_test_server
      kubernetes_cert:
        from_secret: rke_test_cert
      kubernetes_token:
        from_secret: rke_test_token
    commands:
      - kubectl apply -f dronetest1.yaml
      - kubectl wait --for=condition=complete -f dronetest1.yaml

depends_on:
- image_building