apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    name: dronetest1
  spec: {}
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    generation: 3
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-php
    name: php
    namespace: dronetest1
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-php
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-php
      spec:
        affinity: {}
        containers:
        - image: registry.nextpertise.tools/nextpertise/michaelphp:test1
          imagePullPolicy: Always
          name: nginx
          ports:
          - containerPort: 9000
            name: php
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsConfig: {}
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: harbor
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
    generation: 5
    labels:
      workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-web
    name: web
    namespace: dronetest1
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-web
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-web
      spec:
        affinity: {}
        containers:
        - image: registry.nextpertise.tools/nextpertise/michaelnginx:test1
          imagePullPolicy: Always
          name: nginx
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: harbor
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: php
    labels:
      run: php
  spec:
    ports:
    - port: 9000
      protocol: TCP
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-php
- apiVersion: v1
  kind: Service
  metadata:
    name: web
    labels:
      run: web
  spec:
    ports:
    - port: 80
      protocol: TCP
    selector:
      workload.user.cattle.io/workloadselector: apps.deployment-dronetest1-web
kind: List


